<?php
add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_66df005ae14b6',
	'title' => 'Event',
	'fields' => array(
		array(
			'key' => 'field_66df0d8193db7',
			'label' => 'Event Details',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_66df0d5d93db6',
			'label' => 'Event Type',
			'name' => 'event_type',
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'CAES' => 'CAES',
				'Extension' => 'Extension',
			),
			'default_value' => '',
			'return_format' => 'value',
			'allow_null' => 0,
			'allow_in_bindings' => 1,
			'layout' => 'horizontal',
		),
		array(
			'key' => 'field_66df0ed793db9',
			'label' => 'Title',
			'name' => 'title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66df0f9c93dba',
			'label' => 'Description',
			'name' => 'description',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_66df22f49ed9a',
			'label' => 'Hide Event',
			'name' => 'hide_event',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.33',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'allow_in_bindings' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'ui' => 1,
		),
		array(
			'key' => 'field_66df23119ed9b',
			'label' => 'Show on Master',
			'name' => 'show_on_master',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.33',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'allow_in_bindings' => 1,
			'ui_on_text' => 'No',
			'ui_off_text' => 'Yes',
			'ui' => 1,
		),
		array(
			'key' => 'field_66df0eb793db8',
			'label' => 'Series',
			'name' => 'series',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'series',
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'field_type' => 'checkbox',
			'allow_in_bindings' => 1,
			'bidirectional' => 0,
			'multiple' => 0,
			'allow_null' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_66df22c39ed98',
			'label' => 'Event Scope',
			'name' => 'event_scope',
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'none' => 'None',
				'county' => 'County',
				'radius' => 'Radius',
			),
			'default_value' => '',
			'return_format' => 'value',
			'allow_null' => 0,
			'allow_in_bindings' => 1,
			'layout' => 'horizontal',
		),
		array(
			'key' => 'field_6707fd159478a',
			'label' => 'Counties',
			'name' => 'event_scope_counties',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_66df22c39ed98',
						'operator' => '==',
						'value' => 'county',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'appling' => 'Appling',
				'atkinson' => 'Atkinson',
				'bacon' => 'Bacon',
				'baker' => 'Baker',
				'baldwin' => 'Baldwin',
				'banks' => 'Banks',
				'barrow' => 'Barrow',
				'bartow' => 'Bartow',
				'ben hill' => 'Ben Hill',
				'berrien' => 'Berrien',
				'bibb' => 'Bibb',
				'bleckley' => 'Bleckley',
				'brantley' => 'Brantley',
				'brooks' => 'Brooks',
				'bryan' => 'Bryan',
				'bulloch' => 'Bulloch',
				'burke' => 'Burke',
				'butts' => 'Butts',
				'calhoun' => 'Calhoun',
				'camden' => 'Camden',
				'candler' => 'Candler',
				'carroll' => 'Carroll',
				'catoosa' => 'Catoosa',
				'charlton' => 'Charlton',
				'chatham' => 'Chatham',
				'chattahoochee' => 'Chattahoochee',
				'chattooga' => 'Chattooga',
				'cherokee' => 'Cherokee',
				'clarke' => 'Clarke',
				'clay' => 'Clay',
				'clayton' => 'Clayton',
				'clinch' => 'Clinch',
				'cobb' => 'Cobb',
				'coffee' => 'Coffee',
				'colquitt' => 'Colquitt',
				'columbia' => 'Columbia',
				'cook' => 'Cook',
				'coweta' => 'Coweta',
				'crawford' => 'Crawford',
				'crisp' => 'Crisp',
				'dade' => 'Dade',
				'dawson' => 'Dawson',
				'decatur' => 'Decatur',
				'dekalb' => 'DeKalb',
				'dodge' => 'Dodge',
				'dooly' => 'Dooly',
				'dougherty' => 'Dougherty',
				'douglas' => 'Douglas',
				'early' => 'Early',
				'echols' => 'Echols',
				'effingham' => 'Effingham',
				'elbert' => 'Elbert',
				'emanuel' => 'Emanuel',
				'evans' => 'Evans',
				'fannin' => 'Fannin',
				'fayette' => 'Fayette',
				'floyd' => 'Floyd',
				'forsyth' => 'Forsyth',
				'franklin' => 'Franklin',
				'fulton' => 'Fulton',
				'gilmer' => 'Gilmer',
				'glascock' => 'Glascock',
				'glynn' => 'Glynn',
				'gordon' => 'Gordon',
				'grady' => 'Grady',
				'greene' => 'Greene',
				'gwinnett' => 'Gwinnett',
				'habersham' => 'Habersham',
				'hall' => 'Hall',
				'hancock' => 'Hancock',
				'haralson' => 'Haralson',
				'harris' => 'Harris',
				'hart' => 'Hart',
				'heard' => 'Heard',
				'henry' => 'Henry',
				'houston' => 'Houston',
				'irwin' => 'Irwin',
				'jackson' => 'Jackson',
				'jasper' => 'Jasper',
				'jeff davis' => 'Jeff Davis',
				'jefferson' => 'Jefferson',
				'jenkins' => 'Jenkins',
				'johnson' => 'Johnson',
				'jones' => 'Jones',
				'lamar' => 'Lamar',
				'lanier' => 'Lanier',
				'laurens' => 'Laurens',
				'lee' => 'Lee',
				'liberty' => 'Liberty',
				'lincoln' => 'Lincoln',
				'long' => 'Long',
				'lowndes' => 'Lowndes',
				'lumpkin' => 'Lumpkin',
				'mcduffie' => 'McDuffie',
				'mcintosh' => 'McIntosh',
				'macon' => 'Macon',
				'madison' => 'Madison',
				'marion' => 'Marion',
				'meriwether' => 'Meriwether',
				'miller' => 'Miller',
				'mitchell' => 'Mitchell',
				'monroe' => 'Monroe',
				'montgomery' => 'Montgomery',
				'morgan' => 'Morgan',
				'murray' => 'Murray',
				'muscogee' => 'Muscogee',
				'newton' => 'Newton',
				'oconee' => 'Oconee',
				'oglethorpe' => 'Oglethorpe',
				'paulding' => 'Paulding',
				'peach' => 'Peach',
				'pickens' => 'Pickens',
				'pierce' => 'Pierce',
				'pike' => 'Pike',
				'polk' => 'Polk',
				'pulaski' => 'Pulaski',
				'putnam' => 'Putnam',
				'quitman' => 'Quitman',
				'rabun' => 'Rabun',
				'randolph' => 'Randolph',
				'richmond' => 'Richmond',
				'rockdale' => 'Rockdale',
				'schley' => 'Schley',
				'screven' => 'Screven',
				'seminole' => 'Seminole',
				'spalding' => 'Spalding',
				'stephens' => 'Stephens',
				'stewart' => 'Stewart',
				'sumter' => 'Sumter',
				'talbot' => 'Talbot',
				'taliaferro' => 'Taliaferro',
				'tattnall' => 'Tattnall',
				'taylor' => 'Taylor',
				'telfair' => 'Telfair',
				'terrell' => 'Terrell',
				'thomas' => 'Thomas',
				'tift' => 'Tift',
				'toombs' => 'Toombs',
				'towns' => 'Towns',
				'treutlen' => 'Treutlen',
				'troup' => 'Troup',
				'turner' => 'Turner',
				'twiggs' => 'Twiggs',
				'union' => 'Union',
				'upson' => 'Upson',
				'walker' => 'Walker',
				'walton' => 'Walton',
				'ware' => 'Ware',
				'warren' => 'Warren',
				'washington' => 'Washington',
				'wayne' => 'Wayne',
				'webster' => 'Webster',
				'wheeler' => 'Wheeler',
				'white' => 'White',
				'whitfield' => 'Whitfield',
				'wilcox' => 'Wilcox',
				'wilkes' => 'Wilkes',
				'wilkinson' => 'Wilkinson',
				'worth' => 'Worth',
			),
			'default_value' => array(
			),
			'return_format' => 'value',
			'multiple' => 1,
			'allow_null' => 0,
			'allow_in_bindings' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_6707fe449478b',
			'label' => 'Radius',
			'name' => 'event_scope_radius',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_66df22c39ed98',
						'operator' => '==',
						'value' => 'radius',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => '',
			'max' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66df101f93dbc',
			'label' => 'Location',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_66df104a93dbe',
			'label' => 'County Office',
			'name' => 'location_county_office',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_66df0d5d93db6',
						'operator' => '==',
						'value' => 'Extension',
					),
					array(
						'field' => 'field_66df10cf93dc0',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Sydney Opera House' => 'Sydney Opera House',
				'Eiffel Tower' => 'Eiffel Tower',
				'Statue of Liberty' => 'Statue of Liberty',
				'Great Wall of China' => 'Great Wall of China',
				'Taj Mahal' => 'Taj Mahal',
				'Christ the Redeemer' => 'Christ the Redeemer',
				'Mount Everest' => 'Mount Everest',
				'Colosseum' => 'Colosseum',
				'Pyramids of Giza' => 'Pyramids of Giza',
				'Machu Picchu' => 'Machu Picchu',
			),
			'default_value' => false,
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 1,
			'allow_in_bindings' => 1,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_66df10ba93dbf',
			'label' => 'CAES Rooms/Buildings',
			'name' => 'location_caes_room',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_66df0d5d93db6',
						'operator' => '==',
						'value' => 'CAES',
					),
					array(
						'field' => 'field_66df10cf93dc0',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'Sydney Opera House' => 'Sydney Opera House',
				'Eiffel Tower' => 'Eiffel Tower',
				'Statue of Liberty' => 'Statue of Liberty',
				'Great Wall of China' => 'Great Wall of China',
				'Taj Mahal' => 'Taj Mahal',
				'Christ the Redeemer' => 'Christ the Redeemer',
				'Mount Everest' => 'Mount Everest',
				'Colosseum' => 'Colosseum',
				'Pyramids of Giza' => 'Pyramids of Giza',
				'Machu Picchu' => 'Machu Picchu',
			),
			'default_value' => false,
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 1,
			'allow_in_bindings' => 1,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_66df10cf93dc0',
			'label' => 'Custom Location',
			'name' => 'location_custom',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_66df103193dbd',
						'operator' => '==',
						'value' => 'physical',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'allow_in_bindings' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'ui' => 1,
		),
		array(
			'key' => 'field_66df10e893dc1',
			'label' => 'Google Map',
			'name' => 'location_google_map',
			'aria-label' => '',
			'type' => 'google_map',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_66df10cf93dc0',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'center_lat' => '',
			'center_lng' => '',
			'zoom' => '',
			'height' => '',
			'allow_in_bindings' => 1,
		),
		array(
			'key' => 'field_66df131293dc7',
			'label' => 'Details',
			'name' => 'location_details',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 1,
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
		),
		array(
			'key' => 'field_66df132993dc8',
			'label' => 'Virtual Location',
			'name' => 'location_virtual',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 1,
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 0,
			'delay' => 0,
		),
		array(
			'key' => 'field_66df144d93dc9',
			'label' => 'Date & Time',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_66df150393dca',
			'label' => 'Event Date Type',
			'name' => 'event_date_type',
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'single' => 'Single Day',
				'multi' => 'Multi Day',
			),
			'default_value' => '',
			'return_format' => 'value',
			'allow_null' => 0,
			'allow_in_bindings' => 1,
			'layout' => 'horizontal',
		),
		array(
			'key' => 'field_66df1768e7a6a',
			'label' => 'Start Date',
			'name' => 'start_date',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'F j, Y',
			'return_format' => 'Ymd',
			'first_day' => 1,
			'allow_in_bindings' => 1,
		),
		array(
			'key' => 'field_66df19402eada',
			'label' => 'End Date',
			'name' => 'end_date',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_66df150393dca',
						'operator' => '==',
						'value' => 'multi',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'F j, Y',
			'return_format' => 'Ymd',
			'first_day' => 1,
			'allow_in_bindings' => 1,
		),
		array(
			'key' => 'field_66df1780e7a6b',
			'label' => 'Start Time',
			'name' => 'start_time',
			'aria-label' => '',
			'type' => 'time_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'g:i a',
			'return_format' => 'g:i a',
			'allow_in_bindings' => 1,
		),
		array(
			'key' => 'field_66df18cae7a6c',
			'label' => 'End Time',
			'name' => 'end_time',
			'aria-label' => '',
			'type' => 'time_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'g:i a',
			'return_format' => 'g:i a',
			'allow_in_bindings' => 1,
		),
		array(
			'key' => 'field_66df1c139ed90',
			'label' => 'Occurrence',
			'name' => 'occurrence',
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'one-time' => 'One Time',
				'daily' => 'Daily',
				'weekly' => 'Weekly',
				'monthly' => 'Monthly',
				'annual' => 'Annually',
			),
			'default_value' => '',
			'return_format' => 'value',
			'allow_null' => 0,
			'allow_in_bindings' => 1,
			'layout' => 'horizontal',
		),
		array(
			'key' => 'field_66df21089ed95',
			'label' => 'Publish/Display Date',
			'name' => 'publish_display_date',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'F j, Y',
			'return_format' => 'Ymd',
			'first_day' => 1,
			'allow_in_bindings' => 1,
		),
		array(
			'key' => 'field_66df211c9ed96',
			'label' => 'Date Attachments',
			'name' => 'date_attachments',
			'aria-label' => '',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_66df22a59ed97',
			'label' => 'Registration & Attendance',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_66df22d19ed99',
			'label' => 'Registration Status',
			'name' => 'registration_status',
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'open' => 'Open',
				'closed' => 'Closed',
			),
			'default_value' => '',
			'return_format' => 'value',
			'allow_null' => 0,
			'allow_in_bindings' => 1,
			'layout' => 'horizontal',
		),
		array(
			'key' => 'field_66df26099ed9c',
			'label' => 'Cost',
			'name' => 'cost',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => '',
			'max' => '',
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66df26299ed9d',
			'label' => 'Registration Info',
			'name' => 'registration_info',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 1,
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_66df268c9ed9e',
			'label' => 'Registration Link',
			'name' => 'registration_link',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 1,
			'placeholder' => '',
		),
		array(
			'key' => 'field_66df26a29ed9f',
			'label' => 'Parking Info',
			'name' => 'parking_info',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 1,
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_66df26ba9eda0',
			'label' => 'Contact',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_66f190dc22746',
			'label' => 'Contact Type',
			'name' => 'contact_type',
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'default' => 'Default',
				'custom' => 'Custom',
			),
			'default_value' => '',
			'return_format' => 'value',
			'allow_null' => 0,
			'allow_in_bindings' => 0,
			'layout' => 'horizontal',
		),
		array(
			'key' => 'field_66df27e39eda7',
			'label' => 'Display Contact Information',
			'name' => 'display_contact_information',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'allow_in_bindings' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'ui' => 1,
		),
		array(
			'key' => 'field_66f1907922745',
			'label' => 'Contact',
			'name' => 'contact',
			'aria-label' => '',
			'type' => 'user',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_66f190dc22746',
						'operator' => '==',
						'value' => 'default',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'role' => '',
			'return_format' => 'array',
			'multiple' => 0,
			'allow_null' => 0,
			'allow_in_bindings' => 0,
			'bidirectional' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_66df27649eda2',
			'label' => 'Custom Contact',
			'name' => 'custom_contact',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_66f190dc22746',
						'operator' => '==',
						'value' => 'custom',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_66df27829eda3',
					'label' => 'Name',
					'name' => 'contact_name',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_66df278c9eda4',
					'label' => 'Email',
					'name' => 'contact_email',
					'aria-label' => '',
					'type' => 'email',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_66df27a99eda5',
					'label' => 'Phone',
					'name' => 'contact_phone',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		),
		array(
			'key' => 'field_66df27bf9eda6',
			'label' => 'Approving Admin',
			'name' => 'approving_admin',
			'aria-label' => '',
			'type' => 'user',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'role' => '',
			'return_format' => 'array',
			'multiple' => 0,
			'allow_null' => 0,
			'allow_in_bindings' => 1,
			'bidirectional' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_66df28109eda8',
			'label' => 'Media & Documents',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_66df0fb693dbb',
			'label' => 'Featured Image',
			'name' => 'featured_image',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_66f1a47428335',
			'label' => 'Gallery',
			'name' => 'gallery',
			'aria-label' => '',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'library' => 'all',
			'min' => '',
			'max' => '',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'insert' => 'append',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_66df28939eda9',
			'label' => 'Documents',
			'name' => 'documents',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Document',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_66df28bf9edaa',
					'label' => 'Document Type',
					'name' => 'document_type',
					'aria-label' => '',
					'type' => 'button_group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'link' => 'Link',
						'file' => 'File',
					),
					'default_value' => '',
					'return_format' => 'value',
					'allow_null' => 0,
					'allow_in_bindings' => 1,
					'layout' => 'horizontal',
					'parent_repeater' => 'field_66df28939eda9',
				),
				array(
					'key' => 'field_66df28ff9edab',
					'label' => 'Link',
					'name' => 'lin',
					'aria-label' => '',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_66df28bf9edaa',
								'operator' => '==',
								'value' => 'link',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'parent_repeater' => 'field_66df28939eda9',
				),
				array(
					'key' => 'field_66df29519edad',
					'label' => 'File',
					'name' => 'file',
					'aria-label' => '',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_66df28bf9edaa',
								'operator' => '==',
								'value' => 'file',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => '',
					'allow_in_bindings' => 1,
					'parent_repeater' => 'field_66df28939eda9',
				),
			),
		),
		array(
			'key' => 'field_66df31669edaf',
			'label' => 'Destiny One',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_66df317d9edb0',
			'label' => 'Activate',
			'name' => 'activate',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'allow_in_bindings' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'ui' => 1,
		),
		array(
			'key' => 'field_66df328d9edb1',
			'label' => 'Registration Start Date',
			'name' => 'registration_start_date',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
			'allow_in_bindings' => 1,
		),
		array(
			'key' => 'field_66df34699edb2',
			'label' => 'Registration End Date',
			'name' => 'registration_end_date',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
			'allow_in_bindings' => 1,
		),
		array(
			'key' => 'field_66df34829edb3',
			'label' => 'Max Participants',
			'name' => 'max_participants',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => '',
			'max' => '',
			'allow_in_bindings' => 1,
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66df349f9edb4',
			'label' => 'Min Participants',
			'name' => 'min_participants',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => '',
			'max' => '',
			'allow_in_bindings' => 1,
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66df34dc9edb5',
			'label' => 'Max Waitlist',
			'name' => 'max_waitlist',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '33.33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => '',
			'max' => '',
			'allow_in_bindings' => 1,
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66df34ee9edb6',
			'label' => 'Allow Group/Family Enrollment',
			'name' => 'allow_group_enrollment',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'allow_in_bindings' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'ui' => 1,
		),
		array(
			'key' => 'field_66df35619edb9',
			'label' => 'Deposit Type',
			'name' => 'deposit_type',
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'full' => 'Full',
				'partial' => 'Partial',
			),
			'default_value' => '',
			'return_format' => 'value',
			'allow_null' => 0,
			'allow_in_bindings' => 1,
			'layout' => 'horizontal',
		),
		array(
			'key' => 'field_66df35759edba',
			'label' => 'Deposit Amount',
			'name' => 'deposit_amount',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_66df35619edb9',
						'operator' => '==',
						'value' => 'partial',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => '',
			'max' => '',
			'allow_in_bindings' => 1,
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66df359a9edbb',
			'label' => 'Balance Payment Date',
			'name' => 'balance_payment_date',
			'aria-label' => '',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_66df35619edb9',
						'operator' => '==',
						'value' => 'partial',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
			'allow_in_bindings' => 1,
		),
		array(
			'key' => 'field_66df35b59edbc',
			'label' => 'Additional info',
			'name' => 'additional_info',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'events',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );

	acf_add_local_field_group( array(
	'key' => 'group_6706c195cbafa',
	'title' => 'Event Block',
	'fields' => array(
		array(
			'key' => 'field_6707d753f2998',
			'label' => 'Event Range',
			'name' => 'event_range',
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'all' => 'All',
				'limited' => 'Limited',
				'specific' => 'Specific',
				'for_you' => 'For You',
			),
			'default_value' => '',
			'return_format' => 'value',
			'allow_null' => 0,
			'allow_in_bindings' => 0,
			'layout' => 'horizontal',
		),
		array(
			'key' => 'field_6706c1962ba0e',
			'label' => 'Series',
			'name' => 'series',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6707d753f2998',
						'operator' => '==',
						'value' => 'limited',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'series',
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'field_type' => 'checkbox',
			'allow_in_bindings' => 0,
			'bidirectional' => 0,
			'multiple' => 0,
			'allow_null' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_6707d889f2999',
			'label' => 'Events',
			'name' => 'events',
			'aria-label' => '',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6707d753f2998',
						'operator' => '==',
						'value' => 'specific',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'events',
			),
			'post_status' => array(
				0 => 'publish',
			),
			'taxonomy' => '',
			'filters' => array(
				0 => 'search',
				1 => 'taxonomy',
			),
			'return_format' => 'id',
			'min' => '',
			'max' => '',
			'allow_in_bindings' => 0,
			'elements' => '',
			'bidirectional' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_6706e67a5b77a',
			'label' => 'Number of Posts',
			'name' => 'number_of_posts',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6707d753f2998',
						'operator' => '!=',
						'value' => 'specific',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'min' => '',
			'max' => '',
			'allow_in_bindings' => 0,
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'caes-hub/event-block',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );
	acf_add_local_field_group( array(
	'key' => 'group_671a6acdf2287',
	'title' => 'Featured Event',
	'fields' => array(
		array(
			'key' => 'field_671a6acdf37e6',
			'label' => 'Event Range',
			'name' => 'event_range',
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'latest' => 'Latest',
				'limited' => 'Limited',
				'specific' => 'Specific',
				'for_you' => 'For You',
			),
			'default_value' => '',
			'return_format' => 'value',
			'allow_null' => 0,
			'allow_in_bindings' => 0,
			'layout' => 'horizontal',
		),
		array(
			'key' => 'field_671a6acdf381c',
			'label' => 'Series',
			'name' => 'series',
			'aria-label' => '',
			'type' => 'taxonomy',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_671a6acdf37e6',
						'operator' => '==',
						'value' => 'limited',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => 'series',
			'add_term' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'return_format' => 'id',
			'field_type' => 'checkbox',
			'allow_in_bindings' => 0,
			'bidirectional' => 0,
			'multiple' => 0,
			'allow_null' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_671a6acdf3851',
			'label' => 'Events',
			'name' => 'events',
			'aria-label' => '',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_671a6acdf37e6',
						'operator' => '==',
						'value' => 'specific',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'events',
			),
			'post_status' => array(
				0 => 'publish',
			),
			'taxonomy' => '',
			'filters' => array(
				0 => 'search',
				1 => 'taxonomy',
			),
			'return_format' => 'id',
			'min' => '',
			'max' => 1,
			'allow_in_bindings' => 0,
			'elements' => '',
			'bidirectional' => 0,
			'bidirectional_target' => array(
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'caes-hub/event-featured',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );
} );
